### ISSUE TITLE
Logo for Timezoner

### ISSUE THREAD

**Issue by Yasujizr** [jsjoeio/timezoner-extension#6]
I ran into your project while you were walking around Github. I design a logo for open source projects to do things I can put in sites like Dribbble, Behance. I can design a Logo for you if you want. What kind of Logo do you want? What are the benefits of the program? What are your favorite logo samples?

If you say these, I can design a logo for you.

**Comment by jsjoeio** [comment]
@Yasujizr That's kind of you to offer but I don't need one. Thank you though!
